# Generated by Django 3.1.6 on 2021-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210202_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
