# Generated by Django 3.1.6 on 2021-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210202_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
